import { Link } from 'react-router'
import { brand } from '../brand'
import { contact } from '../content'
import { DocLayout, type DocSection } from '../components/DocLayout'
import { EVIDENCE_RETENTION_DAYS } from '../lib/runs'

const sections: DocSection[] = [
  {
    id: 'summary',
    title: 'The short version',
    body: (
      <ul>
        <li>We collect what we need to run tests and show you reports. Nothing is sold, and there are no advertising or analytics trackers.</li>
        <li>Emails, long numbers and anything typed into forms are masked in your browser before a snapshot leaves it.</li>
        <li>Screenshots are deleted automatically after {EVIDENCE_RETENTION_DAYS} days. Everything else is yours to export or delete at any time.</li>
      </ul>
    ),
  },
  {
    id: 'collect',
    title: 'What we collect',
    body: (
      <>
        <h3>Your account</h3>
        <p>Your email address, and the name and profile picture your sign-in provider (Google or GitHub) shares. Profile details you add in Settings, such as your business name, role, team size and website.</p>
        <h3>Test runs</h3>
        <p>The site address, the goal and test user you chose, and for each step: a text outline of the page (buttons, links, headings, visible errors and whether a form field is filled, never its value), the action taken, the test user's thoughts, and accessibility and page-speed measurements.</p>
        <p>Up to eight screenshots per run of the tab being tested. Form fields are visually masked and Scout is hidden before each capture.</p>
        <h3>Instant Scans</h3>
        <p>The address you scan and the public pages we read from it. Your network address is used briefly to limit scans to five an hour and is not stored with the report. If you give an email address for the report, it is used once to send it and is not stored.</p>
        <h3>Weekly watch and competitor comparisons (paid plans)</h3>
        <p>The sites you choose to watch, when each was last checked and what changed, and the report of every check. For a comparison, the addresses you enter and the public pages we read from each of them, the same way a search engine reads a public page. We only read public pages of sites you do not own.</p>
        <h3>API keys and deploy hooks</h3>
        <p>When you create an API key for the MCP server or a deploy hook for a watched site, we store only a one-way fingerprint (a SHA-256 hash) of it, never the key itself, plus its name and when it was last used. Scans your editor starts through MCP are saved as runs in your account like any other.</p>
      </>
    ),
  },
  {
    id: 'use',
    title: 'How we use it',
    body: (
      <ul>
        <li>To run your tests and scans and to write, store and show your reports.</li>
        <li>To email a report when you ask for it.</li>
        <li>To keep the service working and safe, for example to enforce limits and investigate errors.</li>
        <li>To record how many AI tokens each run used, so we can keep prices sustainable.</li>
      </ul>
      ),
  },
  {
    id: 'ai',
    title: 'AI processing',
    body: (
      <>
        <p>Test users and report summaries are generated by AI models from third-party providers. They receive the masked text outline of each page, the goal and earlier steps. They do not receive your password, cookies or the values typed into forms.</p>
        <p>We do not use your runs to train models. Providers process requests under their API terms.</p>
      </>
    ),
  },
  {
    id: 'processors',
    title: 'Who we share it with',
    body: (
      <>
        <p>Only the service providers that run {brand.name} for us:</p>
        <dl>
          <dt>Supabase</dt>
          <dd>Sign-in, database and private screenshot storage.</dd>
          <dt>Groq and Google (Gemini)</dt>
          <dd>AI models for test users and report writing.</dd>
          <dt>OpenRouter</dt>
          <dd>AI models for Scout, the assistant in team workspace chat. Only when someone asks Scout a question, it receives that question and the workspace's shared findings, report summaries and recent messages.</dd>
          <dt>Google PageSpeed Insights</dt>
          <dd>Mobile speed measurements for the public address being scanned.</dd>
          <dt>Resend</dt>
          <dd>Sending reports by email, only when you ask.</dd>
        </dl>
        <p>A report becomes visible to others only when you create a public link for it, or share it into a team workspace, where that workspace's members can read it. Instant Scan reports have a public link by design. In a team workspace, the other members see your name and email address and what you post there.</p>
      </>
    ),
  },
  {
    id: 'retention',
    title: 'How long we keep it',
    body: (
      <ul>
        <li>Screenshots: deleted automatically {EVIDENCE_RETENTION_DAYS} days after the run.</li>
        <li>Emails entered for an Instant Scan report: not stored; used once to send the report.</li>
        <li>API keys, deploy hooks and watched sites: kept until you revoke or remove them, or delete your account.</li>
        <li>Runs, steps and reports: kept until you delete them.</li>
        <li>Team workspace chat, comments and activity: kept until the author deletes a message or the owner deletes the workspace. When you delete your account, what you wrote in other people's workspaces stays, signed "Former member" instead of your name.</li>
        <li>Your account: kept until you delete it. Deleting it removes every run, report and screenshot, then the account itself.</li>
      </ul>
    ),
  },
  {
    id: 'rights',
    title: 'Your choices and rights',
    body: (
      <>
        <p>From <Link to="/app/settings">Settings</Link> you can download everything we hold about you as one file, and permanently delete your account. You can delete a single run from its report.</p>
        <p>You can also ask us to access, correct or delete your information, or object to how we use it, by emailing <a href={`mailto:${contact.privacy}`}>{contact.privacy}</a>. We reply within 30 days.</p>
      </>
    ),
  },
  {
    id: 'storage',
    title: 'Cookies and local storage',
    body: <p>We do not use advertising or analytics cookies. Your browser stores your sign-in session so you stay signed in, and the extension stores its connection to your account. Both are removed when you sign out.</p>,
  },
  {
    id: 'security',
    title: 'Security',
    body: <p>Data is encrypted in transit, every database table only returns rows to their owner, and screenshots sit in private storage behind short-lived links. Read more on our <Link to="/security">security page</Link>.</p>,
  },
  {
    id: 'children',
    title: 'Children',
    body: <p>{brand.name} is a tool for businesses and developers and is not meant for anyone under 16.</p>,
  },
  {
    id: 'changes',
    title: 'Changes and contact',
    body: <p>If we change this policy in a way that matters, we will update the date above and tell signed-in users before it takes effect. Questions go to <a href={`mailto:${contact.privacy}`}>{contact.privacy}</a>.</p>,
  },
]

export default function Privacy() {
  return (
    <DocLayout
      title="Privacy policy"
      lead={`What ${brand.name} collects when you scan or test a site, why, who processes it and how to take it with you or delete it.`}
      updated="2026-09-25"
      sections={sections}
    />
  )
}
